id: I6DEE0701
default_language: en
source: https://www2.hf.uio.no/polyglotta/index.php?page=library&bid=2
initial_creation_type: input
imported: 2023-02-08 14:52:47.453691
last_modified: 2023-02-08 14:52:47.453827
source_metadata:
  title: 'PP: Aṣṭasāhasrikā Prajñāpāramitā'
  language: en
bases:
  '8527':
    base_file: 8527.txt
    order: 1
copyright:
  status: Unknown
  notice: ''
